export const ADD_DRIVER = 'ADD_DRIVER'
export const GET_DRIVERS= 'GET_DRIVERS'
export const GET_DRIVER = 'GET_DRIVER'
export const DELETE_DRIVER = 'DELETE_DRIVER'
export const DELETE_DRIVERS = 'DELETE_DRIVERS'
export const UPDATE_DRIVER = 'UPDATE_DRIVER'

